// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alkfuelvaxuktjuasuml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsa2Z1ZWx2YXh1a3RqdWFzdW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDcyMzMsImV4cCI6MjA1ODgyMzIzM30.5kRi4Z4igon8DF17Wdy-mXRicSAd2-8-vBzbEfs0uPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);